// <auto-generated />
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Produto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<int>("ID_UsuarioCriacao")
                    .HasColumnType("int");

                b.Property<int>("ID_UsuarioAlteracao")
                    .HasColumnType("int");

                b.Property<string>("Nome")
                    .HasColumnType("nvarchar(max)");

                b.Property<float>("Preco")
                    .HasColumnType("real");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.HasIndex("ID_UsuarioCriacao");

                b.HasIndex("ID_UsuarioAlteracao");

                b.ToTable("Produtos");
            });

            modelBuilder.Entity("API.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("Nome")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Senha")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("API.Models.Produto", b =>
            {
                b.HasOne("API.Models.Usuario", "UsuarioCriacao")
                    .WithMany()
                    .HasForeignKey("ID_UsuarioCriacao")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("API.Models.Usuario", "UsuarioAlteracao")
                    .WithMany()
                    .HasForeignKey("ID_UsuarioAlteracao")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("UsuarioCriacao");

                b.Navigation("UsuarioAlteracao");
            });
#pragma warning restore 612, 618
        }
    }
}
